version: "3.8"
services:
  app:
    build: .
    container_name: emgt
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employee_mgt
    volumes:
      - ./pgdata:/var/lib/postgres/data
